#!/usr/bin/env bash
# install-pi.sh — Paramant Relay installer for Raspberry Pi
# Supports: Pi 3B+, Pi 4, Pi 5  |  Raspberry Pi OS Lite 64-bit (ARM64)
# Usage: curl -fsSL https://paramant.app/install-pi.sh | bash

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

REPO_URL="https://github.com/Apolloccrypt/paramant-relay.git"
INSTALL_DIR="/opt/paramant-relay"

# ── Helpers ───────────────────────────────────────────────────────────────────
step() { echo -e "\n${CYAN}${BOLD}▶ $*${RESET}"; }
ok()   { echo -e "  ${GREEN}✓${RESET} $*"; }
warn() { echo -e "  ${YELLOW}⚠${RESET}  $*"; }
die()  { echo -e "\n${RED}${BOLD}✗ $*${RESET}\n"; exit 1; }

banner() {
  echo -e "${CYAN}${BOLD}"
  echo "  ╔═══════════════════════════════════════╗"
  echo "  ║     PARAMANT RELAY — Pi Installer     ║"
  echo "  ║   Post-quantum encrypted file relay   ║"
  echo "  ╚═══════════════════════════════════════╝"
  echo -e "${RESET}"
}

# ── Pi detection ──────────────────────────────────────────────────────────────
detect_pi() {
  if grep -qi "Raspberry Pi" /proc/cpuinfo 2>/dev/null || \
     grep -qi "BCM" /proc/cpuinfo 2>/dev/null || \
     [ -f /proc/device-tree/model ] && grep -qi "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
    MODEL=$(tr -d '\0' < /proc/device-tree/model 2>/dev/null || grep "Model" /proc/cpuinfo | head -1 | cut -d: -f2 | xargs || echo "Raspberry Pi")
    ok "Detected: ${MODEL}"
    return 0
  fi
  warn "This doesn't look like a Raspberry Pi."
  echo -e "  ${DIM}Continue anyway? [y/N]${RESET} \c"
  read -r reply
  [[ "$reply" =~ ^[Yy]$ ]] || die "Aborted — not a Raspberry Pi."
}

# ── Root check ────────────────────────────────────────────────────────────────
require_root() {
  [[ $EUID -eq 0 ]] || die "Run as root: sudo bash install-pi.sh"
}

# ── Docker install ────────────────────────────────────────────────────────────
install_docker() {
  if command -v docker &>/dev/null; then
    ok "Docker already installed ($(docker --version | cut -d' ' -f3 | tr -d ','))"
    return
  fi
  step "Installing Docker"
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed"

  # Add pi / current user to docker group
  for u in pi "${SUDO_USER:-}" ubuntu; do
    id "$u" &>/dev/null && usermod -aG docker "$u" && ok "Added $u to docker group" && break
  done
}

# ── Disable swap ──────────────────────────────────────────────────────────────
disable_swap() {
  step "Disabling swap (relay is RAM-only — swap would write plaintext to disk)"
  swapoff -a
  # Remove swap entries from fstab
  sed -i '/\bswap\b/d' /etc/fstab
  # Disable dphys-swapfile if present
  if systemctl is-enabled dphys-swapfile &>/dev/null; then
    systemctl disable --now dphys-swapfile
    ok "dphys-swapfile disabled"
  fi
  ok "Swap disabled"
}

# ── WiFi power save ───────────────────────────────────────────────────────────
disable_wifi_powersave() {
  step "Disabling WiFi power saving (prevents relay connection drops)"
  # Persistent udev rule — survives reboots
  cat > /etc/udev/rules.d/70-wifi-powersave.rules <<'EOF'
SUBSYSTEM=="net", ACTION=="add", KERNEL=="wlan*", RUN+="/sbin/iw dev $name set power_save off"
EOF
  # Apply immediately if wlan0 is up
  if ip link show wlan0 &>/dev/null; then
    iw dev wlan0 set power_save off 2>/dev/null && ok "WiFi power save off (wlan0)" || warn "Could not set power_save now — will apply after reboot"
  else
    ok "WiFi power save rule written (no wlan0 detected — will apply if you add WiFi)"
  fi
}

# ── Clone / update repo ───────────────────────────────────────────────────────
setup_repo() {
  step "Setting up Paramant Relay"
  if [ -d "$INSTALL_DIR/.git" ]; then
    ok "Repo already present — pulling latest"
    git -C "$INSTALL_DIR" pull --ff-only
  else
    git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
    ok "Cloned paramant-relay to $INSTALL_DIR"
  fi
}

# ── Generate .env ─────────────────────────────────────────────────────────────
setup_env() {
  step "Generating .env"
  ENV_FILE="$INSTALL_DIR/.env"
  if [ -f "$ENV_FILE" ]; then
    ok ".env already exists — not overwriting (delete $ENV_FILE to regenerate)"
    return
  fi

  ADMIN_TOKEN=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48)
  LOCAL_IP=$(hostname -I | awk '{print $1}')

  cat > "$ENV_FILE" <<EOF
# Generated by install-pi.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Keep this file secret — do not commit to git

ADMIN_TOKEN=${ADMIN_TOKEN}

# Domain: set to your Pi's hostname or IP for TLS
DOMAIN=${LOCAL_IP}

# Port overrides (default 80/443)
# HTTP_PORT=80
# HTTPS_PORT=443

# Optional — email delivery for API key welcome mails
# RESEND_API_KEY=re_xxxx

# Optional — TOTP MFA seed for admin panel
# TOTP_SECRET=BASE32_SECRET_HERE
EOF
  chmod 600 "$ENV_FILE"
  ok ".env written with auto-generated ADMIN_TOKEN"
  echo -e "  ${DIM}ADMIN_TOKEN: ${ADMIN_TOKEN}${RESET}"
  echo -e "  ${YELLOW}Save this token — you'll need it to manage API keys.${RESET}"
}

# ── Enable Docker at boot ─────────────────────────────────────────────────────
enable_docker_boot() {
  step "Enabling Docker at boot"
  systemctl enable docker
  ok "Docker enabled (starts automatically on reboot)"
}

# ── Start relay stack ─────────────────────────────────────────────────────────
start_relay() {
  step "Pulling images and starting relay stack"
  cd "$INSTALL_DIR"
  docker compose pull
  docker compose up -d
  ok "Relay stack started"
}

# ── QR code + URLs ────────────────────────────────────────────────────────────
show_access_info() {
  LOCAL_IP=$(hostname -I | awk '{print $1}')
  DASHBOARD_URL="http://${LOCAL_IP}/dashboard"

  step "Done!"
  echo ""
  echo -e "  ${BOLD}Access URLs${RESET}"
  echo -e "  ${GREEN}Dashboard :${RESET}  http://${LOCAL_IP}/dashboard"
  echo -e "  ${GREEN}Health    :${RESET}  http://${LOCAL_IP}/rp/health/health"
  echo -e "  ${GREEN}Legal     :${RESET}  http://${LOCAL_IP}/rp/legal/health"
  echo -e "  ${GREEN}Finance   :${RESET}  http://${LOCAL_IP}/rp/finance/health"
  echo -e "  ${GREEN}IoT       :${RESET}  http://${LOCAL_IP}/rp/iot/health"
  echo ""

  # Show QR code if qrencode is available (or install it)
  if ! command -v qrencode &>/dev/null; then
    apt-get install -y -qq qrencode 2>/dev/null || true
  fi

  if command -v qrencode &>/dev/null; then
    echo -e "  ${BOLD}Scan to open dashboard:${RESET}"
    echo ""
    qrencode -t ANSIUTF8 -m 2 "$DASHBOARD_URL"
    echo ""
  else
    echo -e "  ${DIM}(Install qrencode to show a QR code: apt install qrencode)${RESET}"
    echo ""
  fi

  echo -e "  ${BOLD}Next steps:${RESET}"
  echo -e "  1. Add API keys:  edit ${INSTALL_DIR}/config/users.json"
  echo -e "  2. Check logs:    docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f"
  echo -e "  3. Full docs:     https://github.com/Apolloccrypt/paramant-relay"
  echo ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  banner
  require_root
  step "Detecting hardware"
  detect_pi
  install_docker
  disable_swap
  disable_wifi_powersave
  setup_repo
  setup_env
  enable_docker_boot
  start_relay
  show_access_info
}

main "$@"
