#!/usr/bin/env python3
"""Generate frontend/sitemap.xml from what is actually on disk.

The hand-maintained sitemap drifted: it carried a lastmod of 2026-04-20 on
almost every entry while pages had changed since, and ten help articles plus
nine product pages were missing entirely because nobody remembered to add them.
A generated sitemap cannot drift.

lastmod comes from git (the last commit that touched the file), falling back to
the file's mtime, so the date means something instead of being a copy-paste.

Run: python3 bron-seo/build_sitemap.py [--check]
"""
import os
import re
import subprocess
import sys
from datetime import date, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRONTEND = os.path.join(ROOT, "frontend")
ORIGIN = "https://paramant.app"
OUT = os.path.join(FRONTEND, "sitemap.xml")
SKIP_DIRS = {"node_modules", "vendor"}

# Keep in step with PRIVATE in tests/seo-contract.test.mjs and apply_seo_head.py.
PRIVATE = {
    "404", "account", "admin", "all-systems-go", "claim", "co-sign", "dashboard",
    "developer", "get", "ontvang", "request-key", "setup",
    "auth/backup", "auth/login", "auth/request-reset", "auth/reset-confirm",
    "auth/setup", "billing/checkout", "signup/verified",
}

# Crawl priority. Not a ranking factor, but it tells a crawler where to spend
# its budget on a 60-page site: the product and the money pages first.
PRIORITY = [
    (0.9, {"index", "pricing", "sign", "parashare", "verify", "vault", "paraid", "download"}),
    (0.8, {"security", "sovereignty", "trust", "architecture", "docs", "vs", "about"}),
]
DEFAULT_PRIORITY = 0.6

# Meta-refresh stubs. They keep their canonical to the real page and stay out
# of the sitemap; listing a redirect wastes crawl budget on a page with no
# content of its own.
REDIRECTS = {"iot"}


def slugs():
    found = []
    for base, dirs, files in os.walk(FRONTEND):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fn in files:
            if not fn.endswith(".html"):
                continue
            rel = os.path.relpath(os.path.join(base, fn), FRONTEND)
            slug = rel[:-5].replace(os.sep, "/")
            if slug not in PRIVATE and slug not in REDIRECTS:
                found.append((slug, os.path.join(base, fn)))
    return sorted(found)


def url_for(slug):
    if slug == "index":
        return ORIGIN + "/"
    if slug.endswith("/index"):
        return f"{ORIGIN}/{slug[:-len('/index')]}"
    return f"{ORIGIN}/{slug}"


def lastmod(path):
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", path],
            cwd=ROOT, capture_output=True, text=True, timeout=15)
        stamp = out.stdout.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", stamp):
            return stamp
    except Exception:
        pass
    return datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d")


def priority(slug):
    for value, group in PRIORITY:
        if slug in group:
            return value
    return DEFAULT_PRIORITY


def build():
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<!-- Generated by bron-seo/build_sitemap.py. Do not edit by hand. -->',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for slug, path in slugs():
        lines += ["  <url>",
                  f"    <loc>{url_for(slug)}</loc>",
                  f"    <lastmod>{lastmod(path)}</lastmod>",
                  f"    <priority>{priority(slug)}</priority>",
                  "  </url>"]
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def main():
    xml = build()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != xml:
            print("sitemap.xml is out of date; run bron-seo/build_sitemap.py")
            return 1
        print("sitemap.xml is up to date")
        return 0
    open(OUT, "w", encoding="utf-8").write(xml)
    print(f"wrote {OUT} with {xml.count('<url>')} urls")
    return 0


if __name__ == "__main__":
    sys.exit(main())
